kind: Service
apiVersion: v1
metadata:
  name: plane-nats-ext
spec:
  selector:
    app.kubernetes.io/name: nats
  ports:
  - name: client
    protocol: TCP
    port: 4222
    nodePort: 30303
  - name: monitor
    port: 8222
  # - name: metrics
  #   port: 7777
  type: NodePort