diff --git a/Makefile b/Makefile
index 1f30f6f..9461501 100644
--- a/Makefile
+++ b/Makefile
@@ -119,12 +119,13 @@ ifeq ($(RTLSDR), yes)
 
     # some linux librtlsdr packages return a bare -L with no path in --libs
     # which horribly confuses things because it eats the next option on the command line
-    RTLSDR_LFLAGS := $(shell pkg-config --libs-only-L librtlsdr)
-    ifeq ($(RTLSDR_LFLAGS),-L)
-      LIBS_SDR += $(shell pkg-config --libs-only-l --libs-only-other librtlsdr)
-    else
-      LIBS_SDR += $(shell pkg-config --libs librtlsdr)
-    endif
+    # RTLSDR_LFLAGS := $(shell pkg-config --libs-only-L librtlsdr)
+    # ifeq ($(RTLSDR_LFLAGS),-L)
+    #   LIBS_SDR += $(shell pkg-config --libs-only-l --libs-only-other librtlsdr)
+    # else
+    #   LIBS_SDR += $(shell pkg-config --libs librtlsdr)
+    # endif
+	LIBS_SDR += -lrtlsdr
   endif
 endif
 
